#!/bin/bash
dir=`uname -r`
pwd=`echo linux-headers-${dir}`
function update_whitelist
{
	blacklist_sha1=`sha1sum /etc/antivirusfiles/blacklist`
	whitelist_sha1=`sha1sum /etc/antivirusfiles/whitelist`
	IFS=' ' read -ra blacklist_sha1Arr <<< "$blacklist_sha1"
	IFS=' ' read -ra whitelist_sha1Arr <<< "$whitelist_sha1"
	echo "">>$path/whitelist
	echo ${blacklist_sha1Arr[0]} >> /etc/antivirusfiles/whitelist
	echo ${whitelist_sha1Arr[0]} >> /etc/antivirusfiles/whitelist


}
function build_files
{
	gcc /usr/src/${pwd}/LinuxAntivirus/antivirus_check.c -o /usr/bin/antivirus_scan
	gcc /usr/src/${pwd}/LinuxAntivirus/user.c -o /usr/bin/user
	gcc -w /usr/src/${pwd}/LinuxAntivirus/scripts/testprogram.c -o /usr/src/${pwd}/LinuxAntivirus/scripts/testprogram
}

function copy_and_run_files
{
	
	cp -r /usr/src/${pwd}/LinuxAntivirus/scripts/antivirus_update /usr/bin/
	if [[ -f /etc/antivirusfiles/blacklist && -f /etc/antivirusfiles/whitelist ]];then 
		echo "Whitelist and blacklist file already exists in /etc/antivirusfiles " 
	else
		echo "Adding Blacklist and Whitelist files"
		mkdir -p /etc/antivirusfiles/
		cp -r /usr/src/${pwd}/LinuxAntivirus/testfiles/blacklist /etc/antivirusfiles/
		cp -r /usr/src/${pwd}/LinuxAntivirus/testfiles/whitelist /etc/antivirusfiles/
		update_whitelist
	fi
	chmod -R 755 /usr/bin/antivirus_update /usr/bin/antivirus_scan
	rm -rf /usr/src/${pwd}/LinuxAntivirus/scripts/nohup.out
	nohup sh /usr/src/${pwd}/LinuxAntivirus/scripts/run_user.sh &
	cd /usr/src/${pwd}/LinuxAntivirus
	sh install.sh
}

var=`lsmod |grep antivirus`
if [[ -z "$var" ]];then
build_files
copy_and_run_files
else
echo "Already Installed"
fi
